import 'package:flutter/material.dart';
import '../models/shop_item.dart';

class ShopRepository {
  List<ShopItem> getCatalog() => _catalog;

  static const List<ShopItem> _catalog = [
    ShopItem(
      id: DefaultItemIds.avatarBoy,
      name: 'Boy',
      description: 'Boy',
      imageAssetPath: 'assets/avatars/boy.svg',
      price: 0,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.base,
    ),
    ShopItem(
      id: DefaultItemIds.avatarGirl,
      name: 'Girl',
      description: 'Girl',
      imageAssetPath: 'assets/avatars/girl.svg',
      price: 0,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.base,
    ),
    ShopItem(
      id: DefaultItemIds.turbanNone,
      name: 'No Turban',
      description: 'Bare-headed.',
      icon: Icons.circle_outlined,
      color: Colors.grey,
      price: 0,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.turban,
    ),
    ShopItem(
      id: 'turban_orange',
      name: 'Orange Turban',
      description: 'A vibrant orange turban.',
      icon: Icons.circle,
      color: Colors.deepOrange,
      price: 100,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.turban,
    ),
    ShopItem(
      id: DefaultItemIds.clothesDefault,
      name: 'Casual Fit',
      description: 'Comfortable everyday clothes.',
      icon: Icons.checkroom,
      color: Colors.brown,
      price: 0,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.clothes,
    ),
    ShopItem(
      id: 'clothes_formal',
      name: 'Formal Outfit',
      description: 'Sharp and sophisticated.',
      icon: Icons.checkroom,
      color: Colors.black87,
      price: 120,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.clothes,
    ),
    ShopItem(
      id: DefaultItemIds.accessoryNone,
      name: 'No Accessory',
      description: 'Keep it simple.',
      icon: Icons.circle_outlined,
      color: Colors.grey,
      price: 0,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.accessory,
    ),
    ShopItem(
      id: 'accessory_glasses',
      name: 'Glasses',
      description: 'For a studious look.',
      icon: Icons.visibility,
      color: Colors.teal,
      price: 80,
      category: ShopItemCategory.avatar,
      avatarSlot: AvatarSlot.accessory,
    ),
    ShopItem(
      id: 'powerup_streak_freeze',
      name: 'Streak Freeze',
      description: 'Protects your streak if you miss a day.',
      icon: Icons.ac_unit,
      color: Colors.lightBlue,
      price: 50,
      category: ShopItemCategory.powerUp,
      stackable: true,
    ),
    ShopItem(
      id: 'powerup_extra_life',
      name: 'Extra Heart',
      description: 'Gives you an extra life in games.',
      icon: Icons.favorite,
      color: Colors.red,
      price: 20,
      category: ShopItemCategory.powerUp,
      stackable: true,
    ),
  ];
}
